### ISSUE TITLE
[1.19] Right clicking anything causes crash

### ISSUE THREAD

**Issue by Baggytrousers27** [willatendo/More-Right-Click-Functions#1]
Forge 41.0.110
morerightclickfunctions-2.2.1 (hotfix)

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock.getPlayer()'
Exit Code: -1

[crashlog](https://github.com/willatendo/More-Right-Click-Functions/files/9175619/crash-2022-07-24_20.45.43-client.txt)

**Comment by willatendo** [comment]
Sorry for getting back so late! I didn't get a notification for this! Your problem is the forge version is too new for this file. I need to update the forge version. Thanks for the report! I will be releasing a 1.19.2 one soon!
